GET http://localhost:3000/movies
###

GET http://localhost:3000/movies/62
###

POST http://localhost:3000/movies/
###


PUT http://localhost:3000/movies/63/
###

DELETE http://localhost:3000/movies/63/
###

GET http://localhost:3000/directors
###

GET http://localhost:3000/directors/3


